"""fix  tables again

Revision ID: 0d5ac9f3849e
Revises: e5cc7b9d727e
Create Date: 2024-07-13 18:18:21.383209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5ac9f3849e'
down_revision: Union[str, None] = 'e5cc7b9d727e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_receiver_username_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'receiver_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('receiver_username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key('messages_receiver_username_fkey', 'messages', 'users', ['receiver_username'], ['username'])
    # ### end Alembic commands ###
