"""fix  tables again

Revision ID: d3eeb888f6d1
Revises: 8826f5f68144
Create Date: 2024-07-09 11:18:17.135648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3eeb888f6d1'
down_revision: Union[str, None] = '8826f5f68144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('receiver_username', sa.String(length=50), nullable=False))
    op.add_column('messages', sa.Column('text', sa.String(), nullable=False))
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['receiver_username'], ['username'])
    op.add_column('users', sa.Column('contacts', sa.ARRAY(sa.INTEGER()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contacts')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'text')
    op.drop_column('messages', 'receiver_username')
    op.drop_column('messages', 'receiver_id')
    # ### end Alembic commands ###
