"""fix  tables again

Revision ID: e5cc7b9d727e
Revises: d3eeb888f6d1
Create Date: 2024-07-13 03:52:57.942082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5cc7b9d727e'
down_revision: Union[str, None] = 'd3eeb888f6d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chats', 'users', ['user_2_id'], ['id'])
    op.create_foreign_key(None, 'chats', 'users', ['user_1_id'], ['id'])
    op.add_column('messages', sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'contacts',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'contacts',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               nullable=False)
    op.drop_column('messages', 'sent_at')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    # ### end Alembic commands ###
